config/routes.rb
EmailSpoofer::Application.routes.draw do
  resources :spoofers

end

app/models/spoofer.rb
class Spoofer < ActiveRecord::Base
validates :from, :to,:presence=>true,:format=>{:with=>/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/,:message=>" : Enter valid email address"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/spoofers_controller.rb
class SpoofersController < ApplicationController
require 'net/smtp'
  # GET /spoofers
  # GET /spoofers.json
  def index
    @spoofers = Spoofer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spoofers }
    end
  end

  # GET /spoofers/1
  # GET /spoofers/1.json
  def show
    @spoofer = Spoofer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spoofer }
    end
  end

  # GET /spoofers/new
  # GET /spoofers/new.json
  def new
    @spoofer = Spoofer.new




    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spoofer }
    end
  end

  # GET /spoofers/1/edit
  def edit
    @spoofer = Spoofer.find(params[:id])
  end

  # POST /spoofers
  # POST /spoofers.json
  def create
    @spoofer = Spoofer.new(params[:spoofer])

    respond_to do |format|
      if @spoofer.save
      msg = ''
    msg+= "Subject: " + @spoofer.subject+"\n"
    msg += "From: "+@spoofer.from+"\n"
    msg += @spoofer.message
	smtp = Net::SMTP.new 'smtp.elasticemail.com',2525
smtp.start("xyz@xyz.com","ego.alternate@gmail.com","e8b741aa-45ff-4cda-9060-d623153d2610",:login) do
	smtp.send_message(msg,@spoofer.from,@spoofer.to)
	end
        format.html { redirect_to @spoofer, notice: 'Spoofer was successfully created.' }
        format.json { render json: @spoofer, status: :created, location: @spoofer }
      else
        format.html { render action: "new" }
        format.json { render json: @spoofer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spoofers/1
  # PUT /spoofers/1.json
  def update
    @spoofer = Spoofer.find(params[:id])

    respond_to do |format|
      if @spoofer.update_attributes(params[:spoofer])
        format.html { redirect_to @spoofer, notice: 'Spoofer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @spoofer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spoofers/1
  # DELETE /spoofers/1.json
  def destroy
    @spoofer = Spoofer.find(params[:id])
    @spoofer.destroy

    respond_to do |format|
      format.html { redirect_to spoofers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spoofers_helper.rb
module SpoofersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmailSpoofer</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spoofers/_form.html.erb
<%= form_for(@spoofer) do |f| %>
  <% if @spoofer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spoofer.errors.count, "error") %> prohibited this spoofer from being saved:</h2>

      <ul>
      <% @spoofer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= f.text_field :to %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit "Send mail" %>
  </div>
<% end %>

app/views/spoofers/edit.html.erb
<h1>Editing spoofer</h1>

<%= render 'form' %>

<%= link_to 'Show', @spoofer %> |
<%= link_to 'Back', spoofers_path %>

app/views/spoofers/index.html.erb
<h1>Sent mails</h1>

<table cellpadding="10px" border>
  <tr>
    <th>From</th>
    <th>To</th>
    <th>Subject</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spoofers.each do |spoofer| %>
  <tr>
    <td><%= spoofer.from %></td>
    <td><%= spoofer.to %></td>
    <td><%= spoofer.subject %></td>
    <td><%= spoofer.message[0,[spoofer.message.length,20].min] %></td>
    <td><%= link_to 'Show', spoofer %></td>
    <td><%= link_to 'Edit', edit_spoofer_path(spoofer) %></td>
    <td><%= link_to 'Delete', spoofer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Send new mail', new_spoofer_path %>

app/views/spoofers/new.html.erb
<h1>Compose mail</h1>

<%= render 'form' %>

<%= link_to 'Back', spoofers_path %>

app/views/spoofers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From:</b>
  <%= @spoofer.from %>
</p>

<p>
  <b>To:</b>
  <%= @spoofer.to %>
</p>

<p>
  <b>Subject:</b>
  <%= @spoofer.subject %>
</p>

<p>
  <b>Message:</b>
  <%= @spoofer.message %>
</p>


<%= link_to 'Edit', edit_spoofer_path(@spoofer) %> |
<%= link_to 'Back', spoofers_path %>